export const HOME_PAGE_PORTFOLIO_CARDS_AMOUNT = 3
export const ABOUT_ME_COLUMNS_AMOUNT = 3
export const FOOTER_COLUMNS_AMOUNT = 3
export const PORTFOLIO_PAGE_COLUMNS_AMOUNT = 3

export const ADMIN_PANEL_LINKS_PER_TABLE = 5